-- DROP TABLE IF EXISTS ORDERS;
-- DROP TABLE IF EXISTS ITEM;
-- DROP TABLE IF EXISTS PRODUCT;
-- DROP SEQUENCE IF EXISTS ORDERS_SEQ;
-- DROP SEQUENCE IF EXISTS ITEM_SEQ;
-- DROP SEQUENCE IF EXISTS PRODUCT_SEQ;
--
-- CREATE TABLE IF NOT EXISTS ORDERS (
--                        ORDER_ID NUMBER PRIMARY KEY NOT NULL,
--                        CUSTOMER_NAME VARCHAR(100) NOT NULL,
--                        CUSTOMER_CONTACT VARCHAR(100) NOT NULL,
--                        SHIPPING_ADDRESS VARCHAR(200) NOT NULL,
--                        GRAND_TOTAL NUMBER NOT NULL,
--                        ORDER_DATE TIMESTAMP(6) WITH TIME ZONE NOT NULL
-- );
--
-- CREATE TABLE PRODUCT (
--                          PRODUCT_ID NUMBER PRIMARY KEY NOT NULL,
--                          NAME VARCHAR(100) NOT NULL,
--                          CATEGORY VARCHAR(100) NOT NULL,
--                          WEIGHT NUMBER NOT NULL,
--                          PRICE NUMBER NOT NULL,
--                          CREATION_DATE TIMESTAMP(6) WITH TIME ZONE NOT NULL
-- );
--
-- CREATE TABLE ITEM (
--                        ITEM_ID NUMBER PRIMARY KEY NOT NULL,
--                        ORDER_ID NUMBER NOT NULL,
--                        PRODUCT_ID NUMBER NOT NULL,
--                        COST NUMBER NOT NULL,
--                        SHIPPING_FEE NUMBER NOT NULL,
--                        TAX_AMOUNT VARCHAR(100) NOT NULL
-- );
-- ALTER TABLE ITEM ADD CONSTRAINT fk_item_order FOREIGN KEY (ORDER_ID) REFERENCES ORDERS (ORDER_ID);
-- ALTER TABLE ITEM ADD CONSTRAINT fk_item_product FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT (PRODUCT_ID);
--
-- CREATE SEQUENCE ORDERS_SEQ INCREMENT BY 1 START WITH 1;
-- CREATE SEQUENCE ITEM_SEQ INCREMENT BY 1 START WITH 1;
-- CREATE SEQUENCE PRODUCT_SEQ INCREMENT BY 1 START WITH 1;

INSERT INTO ORDERS (ORDER_ID, CUSTOMER_NAME, CUSTOMER_CONTACT, SHIPPING_ADDRESS, GRAND_TOTAL, ORDER_DATE) VALUES
(ORDERS_SEQ.NEXTVAL, 'Dangote', 'Billionaire Industrialist 1', 'Address1', 30, to_date('05/12/2019 00:10:00','DD/MM/YYYY HH12:MI:SS')),
(ORDERS_SEQ.NEXTVAL, 'Dangote', 'Billionaire Industrialist 4', 'Address4', 60, to_date('05/08/2020 00:00:00','DD/MM/YYYY HH12:MI:SS')),
(ORDERS_SEQ.NEXTVAL, 'Dangote', 'Billionaire Industrialist 2', 'Address2', 40, to_date('05/12/2020 00:00:00','DD/MM/YYYY HH12:MI:SS')),
(ORDERS_SEQ.NEXTVAL, 'Dangote', 'Billionaire Industrialist 3', 'Address3', 50, to_date('05/01/2021 00:00:00','DD/MM/YYYY HH12:MI:SS'));

INSERT INTO PRODUCT (PRODUCT_ID, NAME, CATEGORY, WEIGHT, PRICE, CREATION_DATE) VALUES
(PRODUCT_SEQ.NEXTVAL, 'Product 1', 'Cosmetic', 10, 30.50, to_date('05/12/2017 00:00:00','DD/MM/YYYY HH12:MI:SS')),
(PRODUCT_SEQ.NEXTVAL, 'Product 2', 'Eletronic', 1000, 2500, to_date('05/02/2020 00:00:00','DD/MM/YYYY HH12:MI:SS')),
(PRODUCT_SEQ.NEXTVAL, 'Product 3', 'Food', 200, 25.30, to_date('05/06/2020 00:00:00','DD/MM/YYYY HH12:MI:SS')),
(PRODUCT_SEQ.NEXTVAL, 'Product 4', 'Drink', 150, 18, to_date('05/09/2020 00:00:00','DD/MM/YYYY HH12:MI:SS')),
(PRODUCT_SEQ.NEXTVAL, 'Product 5', 'Clothes', 500, 203.58, to_date('05/12/2020 00:00:10','DD/MM/YYYY HH12:MI:SS'));

INSERT INTO ITEM (ITEM_ID, ORDER_ID, PRODUCT_ID, COST, SHIPPING_FEE, TAX_AMOUNT) VALUES
(ITEM_SEQ.NEXTVAL, 1, 1, 30.50, 15, 2),
(ITEM_SEQ.NEXTVAL, 1, 2, 2500, 15, 2),
(ITEM_SEQ.NEXTVAL, 2, 2, 2500, 15, 2),
(ITEM_SEQ.NEXTVAL, 3, 3, 25.30, 15, 2),
(ITEM_SEQ.NEXTVAL, 3, 5, 203.58, 15, 2),
(ITEM_SEQ.NEXTVAL, 4, 4, 18, 15, 2);